### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by franciscoliu** [Ladun/BERT-SDA#1]
Hi, Ladun:

I am a college student that just gets into the deep learning field. I was reading the paper: "Improving BERT Fine-Tuning via Self-Ensemble and Self-Distillation" and saw your implementation code. I am just wondering if I could have your email address and discuss a little more about the details of the implementation? (BERT-SDA) Therefore, could you maybe email me your email address? Thank you very much. This is my email address: zheyuanliu@brandeis.edu. Wish to hear from you. 

Best
Frank

**Comment by Ladun** [comment]
I sent it to your email.
